"""empty message

Revision ID: 79149b164a47
Revises: f58659936f2f
Create Date: 2016-08-26 11:06:48.141359

"""

# revision identifiers, used by Alembic.
revision = '79149b164a47'
down_revision = 'f58659936f2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_item', sa.String(length=30), nullable=True))
    # next 2 lines added so that we can add a new column to table, with nullable=false
    # despite fact that previous table entries will have this column blank
    orders = sa.table('orders', sa.column('order_item'))
    op.execute(orders.update().values(order_item=''))
    op.alter_column('orders', 'order_item', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_item')
    ### end Alembic commands ###
