"""empty message

Revision ID: e7df43e635a3
Revises: f86d79a0e3b2
Create Date: 2016-08-26 10:31:03.042887

"""

# revision identifiers, used by Alembic.
revision = 'e7df43e635a3'
down_revision = 'f86d79a0e3b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    ### end Alembic commands ###
