"""empty message

Revision ID: f58659936f2f
Revises: e7df43e635a3
Create Date: 2016-08-26 10:57:00.978077

"""

# revision identifiers, used by Alembic.
revision = 'f58659936f2f'
down_revision = 'e7df43e635a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('order')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=u'order_pkey')
    )
    op.drop_table('orders')
    ### end Alembic commands ###
